// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYQBiNhXdBnO3Bwr1p5FWumft6qOmPfRw',
    appId: '1:722778633635:web:edba01efd751e82e39d616',
    messagingSenderId: '722778633635',
    projectId: 'slowonmove',
    authDomain: 'slowonmove.firebaseapp.com',
    storageBucket: 'slowonmove.firebasestorage.app',
    measurementId: 'G-3FXF21FSFM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZ7m3TVbX2ynHX2ZYLdjY8f0UiX0zScsY',
    appId: '1:722778633635:android:1a877e7ac8a2e27639d616',
    messagingSenderId: '722778633635',
    projectId: 'slowonmove',
    storageBucket: 'slowonmove.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArE2qLKhEVu8SPZYYbZdxv2KtdVaJ2-_o',
    appId: '1:722778633635:ios:f479fa87968afbb739d616',
    messagingSenderId: '722778633635',
    projectId: 'slowonmove',
    storageBucket: 'slowonmove.firebasestorage.app',
    iosBundleId: 'com.showonmove.showOnMove',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArE2qLKhEVu8SPZYYbZdxv2KtdVaJ2-_o',
    appId: '1:722778633635:ios:f479fa87968afbb739d616',
    messagingSenderId: '722778633635',
    projectId: 'slowonmove',
    storageBucket: 'slowonmove.firebasestorage.app',
    iosBundleId: 'com.showonmove.showOnMove',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYQBiNhXdBnO3Bwr1p5FWumft6qOmPfRw',
    appId: '1:722778633635:web:4ac312960b6b09bc39d616',
    messagingSenderId: '722778633635',
    projectId: 'slowonmove',
    authDomain: 'slowonmove.firebaseapp.com',
    storageBucket: 'slowonmove.firebasestorage.app',
    measurementId: 'G-MRWFFTS8P2',
  );
}
