# Generated by Django 4.2.30 on 2026-05-10 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="traininglog",
            name="distance",
            field=models.FloatField(default=0.0),
        ),
    ]
