# Generated by Django 4.2.30 on 2026-05-17 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_traininglog_distance"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="avatar",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="login_provider",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="provider_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
