# Generated by Django 4.2.30 on 2026-05-30 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_member_avatar_member_login_provider_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traininglog',
            name='distance',
        ),
    ]
