# Generated by Django 4.2.30 on 2026-08-08 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_bodyrecord_created_at_bloodpressurerecord"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostWorkoutPlan",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("summary", models.TextField(blank=True)),
                ("difficulty", models.CharField(default="中等", max_length=50)),
                ("total_minutes", models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name="communitypost",
            name="like_count",
        ),
        migrations.AddField(
            model_name="communitypost",
            name="post_type",
            field=models.CharField(
                choices=[("journey", "旅程"), ("plan", "計畫"), ("recipe", "食譜")],
                default="journey",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="communitypost",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name="PostWorkoutPlanStep",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("minutes", models.IntegerField()),
                ("order", models.IntegerField(default=0)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="core.postworkoutplan",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.AddField(
            model_name="postworkoutplan",
            name="post",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="workout_plan",
                to="core.communitypost",
            ),
        ),
        migrations.CreateModel(
            name="PostTag",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tags",
                        to="core.communitypost",
                    ),
                ),
            ],
        ),
    ]
