# Generated by Django 4.2.30 on 2026-09-05 10:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_chatmessage"),
    ]

    operations = [
        migrations.CreateModel(
            name="RunInvitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scheduled_at", models.DateTimeField()),
                (
                    "target_distance_km",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "target_duration_minutes",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待回覆"),
                            ("accepted", "已接受"),
                            ("rejected", "已拒絕"),
                            ("cancelled", "已取消"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "invitee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_run_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "inviter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_run_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["inviter", "created_at"],
                        name="core_runinv_inviter_3f064c_idx",
                    ),
                    models.Index(
                        fields=["invitee", "status", "created_at"],
                        name="core_runinv_invitee_cacafc_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="runinvitation",
            constraint=models.CheckConstraint(
                check=models.Q(("inviter", models.F("invitee")), _negated=True),
                name="run_invitation_not_self",
            ),
        ),
    ]
