# Generated by Django 4.2.30 on 2026-09-05 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_communitygroupinvitation_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommunityGroupActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "exercise_type",
                    models.CharField(
                        choices=[("slow_jogging", "超慢跑"), ("squat", "深蹲")],
                        max_length=20,
                    ),
                ),
                ("scheduled_at", models.DateTimeField()),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_group_activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="core.communitygroup",
                    ),
                ),
            ],
            options={
                "ordering": ["scheduled_at", "created_at"],
            },
        ),
    ]
