# Generated by Django 4.2.30 on 2026-09-07 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_communitygroupjoinrequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pointtransaction',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='pointtransaction',
            name='order_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pointtransaction',
            name='status',
            field=models.CharField(default='completed', max_length=20),
        ),
    ]
