# Generated by Django 4.2.30 on 2026-09-13 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_member_points_pointtransaction_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="postworkoutplanstep",
            name="exercise_type",
            field=models.CharField(
                choices=[("slow_jogging", "超慢跑"), ("squat", "深蹲")],
                default="slow_jogging",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="postworkoutplanstep",
            name="reps",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="postworkoutplanstep",
            name="minutes",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
