# Generated by Django 4.2.30 on 2026-09-14 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_postworkoutplanstep_exercise_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='traininglog',
            name='pain_parts',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
