# Generated by Django 4.2.30 on 2026-09-27 08:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_traininglog_pain_parts"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeatureUnlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("feature_code", models.CharField(max_length=100)),
                (
                    "reference_id",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("unlocked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feature_unlocks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="featureunlock",
            constraint=models.UniqueConstraint(
                fields=("member", "feature_code", "reference_id"),
                name="unique_member_feature_unlock",
            ),
        ),
    ]
