# Generated by Django 4.2.30 on 2026-09-27 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_featureunlock_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pointtransaction",
            name="reference_key",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
