# Generated by Django 4.2.30 on 2026-09-27 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_pointtransaction_reference_key"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="workoutitem",
            constraint=models.UniqueConstraint(
                fields=("member", "menu"), name="unique_member_workout_menu"
            ),
        ),
    ]
