# Generated by Django 4.2.30 on 2026-09-27 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_workoutitem_unique_member_workout_menu"),
    ]

    operations = [
        migrations.AddField(
            model_name="workoutmenu",
            name="difficulty",
            field=models.CharField(default="中等", max_length=50),
        ),
        migrations.AddField(
            model_name="workoutmenu",
            name="total_minutes",
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name="WorkoutMenuStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "exercise_type",
                    models.CharField(
                        choices=[("slow_jogging", "超慢跑"), ("squat", "深蹲")],
                        default="slow_jogging",
                        max_length=30,
                    ),
                ),
                ("minutes", models.IntegerField(blank=True, null=True)),
                ("reps", models.IntegerField(blank=True, null=True)),
                ("order", models.IntegerField(default=0)),
                (
                    "menu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="core.workoutmenu",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
