# Generated by Django 4.2.30 on 2026-09-27 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_workoutmenu_difficulty_workoutmenu_total_minutes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workoutmenu",
            name="source_plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="applied_menus",
                to="core.postworkoutplan",
            ),
        ),
        migrations.AddConstraint(
            model_name="workoutmenu",
            constraint=models.UniqueConstraint(
                fields=("member", "source_plan"),
                name="unique_member_source_workout_plan",
            ),
        ),
    ]
