# Generated by Django 4.2.30 on 2026-09-27 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_traininglog_pain_parts'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='exercise_frequency',
            field=models.CharField(choices=[('1_2', '每週 1–2 次'), ('3_4', '每週 3–4 次'), ('5_plus', '每週 5 次以上')], default='1_2', max_length=20),
        ),
        migrations.AddField(
            model_name='member',
            name='exercise_goal',
            field=models.CharField(choices=[('weight_loss', '減脂'), ('muscle_gain', '增肌'), ('health', '維持健康')], default='health', max_length=30),
        ),
    ]
