# Generated by Django 4.2.30 on 2026-09-28 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_workoutmenusession"),
    ]

    operations = [
        migrations.AddField(
            model_name="workoutmenusession",
            name="menu_title",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="workoutmenusession",
            name="menu",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sessions",
                to="core.workoutmenu",
            ),
        ),
    ]
